site_name: order-management
site_url: https://ricardo17coelho.github.io/order-management
repo_url: https://github.com/ricardo17coelho/order-management
theme:
  name: material
  palette:
    - scheme: default
      primary: deep-orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep-orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant